name: Deployment Exercise 1 # Name of the workflow
on: push # Trigger on push events
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code # from repository
        uses: actions/checkout@v3
      - name: Install dependencies # using npm ci
        run: npm ci # Install dependencies using npm ci
      - name: Lint # code
        run: npm run lint
      - name: Test code # using npm test
        run: npm run test
      - name: Build code # using npm run build
        run: npm run build
      - name: Deploy code # Placeholder for deployment step
        run: echo "Deploying..."